[[language]]
name = "rust"

[language-server.rust-analyzer.config]
checkOnSave = { command = "clippy" }
cargo = { allFeatures = true }

[language-server.rust-analyzer.config.inlayHints]
closureReturnTypeHints.enable = true

[[language]]
name = "python"
language-servers = ["basedpyright", "ruff"]

[language-server.basedpyright]
command = "basedpyright-langserver"
args = ["--stdio"]

[language-server.basedpyright.config]
basedpyright.analysis.diagnosticMode = "openFilesOnly"

[language-server.ruff]
command = "ruff"
args = ["server"]

[[language]]
name = "nix"
language-servers = [ "nil" ]

[language-server.nil]
command = "nil"
formatter = { command = "nixfmt" }

[[language]]
name = "toml"
language-servers = [ "taplo" ]

[language-server.taplo]
command = "taplo"

[[language]]
name = "typst"
language-servers = ["tinymist"]

[language-server.tinymist]
command = "tinymist"

[language-server.tinymist.config]
preview.background.enabled = true
preview.background.args = [
  "--data-plane-host=127.0.0.1:23635",
  "--invert-colors=never",
  "--open"
]
