"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
palette = 'one_dark'
continuation_prompt = ' '

format = """
$username\
$directory\
${custom.git}\
$rust\
$golang\
$python\
$package\
$memory_usage\
$cmd_duration\
$line_break\
$character
"""

[palettes.one_dark]
mono0 = '#d7dae0'
mono1 = '#abb2bf'
mono2 = '#828997'
mono3 = '#5c6370'
mono4 = '#3f4451'
color_red0 = '#e06c75'
color_red1 = '#be5046'
color_green = '#98c379'
color_yellow = '#e5c07b'
color_blue = '#61afef'
color_purple = '#c678dd'
color_cyan = '#56b6c2'
color_orange = '#d19a66'
syntax_fg = '#abb2bf'
syntax_bg = '#282c34'
color_bg2 = '#665c54'
syntax_gutter = '#647382'
syntax_accent = "#528cff"

color_ok = '#98c379'
color_danger = '#be5046'
color_caution = '#d19a66'

color_username = '#e06c75'
color_directory = '#e5c07b'
color_git = '#61afef'
color_git_added = '#98c379'
color_git_deleted = '#be5046'
color_env = '#c678dd'
color_docker = '#56b6c2'
color_shell = '#56b6c2'
color_container = '#56b6c2'
color_other = '#56b6c2'
color_duration = '#528cff'

[username]
show_always = true
style_user = "fg:color_username"
style_root = "bold fg:color_danger"
format = '[$user]($style) '

[directory]
style = "fg:color_directory"
read_only_style = "fg:color_directory"
repo_root_style = "bold fg:color_directory"
format = "[$path]($style) "
read_only = ""
home_symbol = "~"
truncation_symbol = "…/"
truncation_length = 3
truncate_to_repo = true
fish_style_pwd_dir_length = 0
use_logical_path = true

[git_branch]
symbol = ""
style = "fg:color_git"
format = '([$symbol $branch]($style))'
only_attached = true
ignore_branches = []
truncation_length = 25
truncation_symbol = "..."
always_show_remote = false
disabled = false

[git_commit]
style = "fg:color_git"
format = "([($tag)(@$hash)]($style))"
commit_hash_length = 7
only_detached = true
tag_symbol = "󰓼 "
tag_disabled = false
disabled = false

[git_status]
style = "fg:color_git"
format = '([$ahead_behind]($style))([$all_status]($style))'
stashed = "*${count}"
ahead = "⇡${count}"
behind = "⇣${count}"
up_to_date = ""
diverged = "⇡${ahead_count}⇣${behind_count}"
conflicted = "=${count}"
deleted = "×${count}"
renamed = "»${count}"
modified = "!${count}"
staged = "+${count}"
untracked = "?${count}"
ignore_submodules = false
disabled = false

[git_state]
style = "fg:color_danger"
format = '([$state($progress_current/$progress_total)]($style bold))'
rebase = "REBASING"
merge = "MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"
disabled = false

[custom.git]
description = "git modules aggregation"
command = '''
    starship module git_branch
    starship module git_commit
    starship module git_status
    starship module git_state
'''
when = "true"
format = "[$output](style) "
require_repo = true
disabled = false

[memory_usage]
style = "fg:color_green"
format = '[${ram}]($style) '
threshold = -1
disabled = false

[cmd_duration]
style = "fg:color_cyan"
min_time = 0
show_milliseconds = true
format = "[$duration](style)"

[character]
success_symbol = "[❯](fg:color_green)"
error_symbol = "[❯](fg:color_danger)"

[c]
symbol = " "
format = '[$symbol($version)]($style)'

[rust]
symbol = ""
format = '[$symbol($version)]($style)'

[golang]
symbol = ""
format = '[$symbol($version)]($style)'

[python]
symbol = " "
format = '[$symbol($version)]($style)'
