"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "vBrunhild"
email = "brunomoretti100@gmail.com"

[signing]
behavior = "own"
backend = "ssh"
key = "~/.ssh/id_ed25519.pub"

[ui]
paginate = "never"
