{
  pkgs,
  ...
}: {
  environment.systemPackages = [
    pkgs.ascii-image-converter
    pkgs.bat
    pkgs.bottom
    pkgs.curl
    pkgs.direnv
    pkgs.fd
    pkgs.fish
    pkgs.git
    pkgs.git-credential-manager
    pkgs.jujutsu
    pkgs.nh
    pkgs.openssh
    pkgs.ripgrep
    pkgs.starship
    pkgs.tealdeer
    pkgs.tinymist
    pkgs.typst
    pkgs.uutils-coreutils-noprefix
    pkgs.wezterm
    pkgs.wikiman
    pkgs.zellij
    pkgs.zoxide
  ];
}
