{pkgs, ...}: {
  environment.systemPackages = [
    pkgs.ascii-image-converter
    pkgs.bat
    pkgs.bottom
    pkgs.curl
    pkgs.direnv
    pkgs.docker
    pkgs.docker-compose
    pkgs.dust
    pkgs.eza
    pkgs.fd
    pkgs.git
    pkgs.git-credential-manager
    pkgs.jujutsu
    pkgs.nh
    pkgs.nushell
    pkgs.openssh
    pkgs.pandoc
    pkgs.ripgrep
    pkgs.sd
    pkgs.tabiew
    pkgs.tealdeer
    pkgs.tinymist
    pkgs.typst
    pkgs.uutils-coreutils-noprefix
    pkgs.wezterm
    pkgs.wikiman
    pkgs.zellij
    pkgs.zoxide
  ];
}
