require("gitsigns").setup({})
require("ibl").setup({})
require("lualine").setup({})
require("nvim-autopairs").setup({})
require("trouble").setup({})
require("colorizer").setup({})
require("Comment").setup({})
require("conform").setup({})
require("guess-indent").setup({})

