require("brunhild.plugins.blink")
require("brunhild.plugins.telescope")
require("brunhild.plugins.minifiles")
require("brunhild.plugins.miniclue")
require("brunhild.plugins.treesitter")
require("brunhild.plugins.conform")
require("brunhild.plugins.dap")
require("brunhild.plugins.statusline")

require("colorizer").setup({})
require("guess-indent").setup({})
require("dap-view").setup({})
require("mini.icons").setup({})
require("mini.comment").setup({})
require("mini.keymap").setup({})
require("mini.pairs").setup({})
require("mini.git").setup({})
require("mini.diff").setup({})
require("mini.trailspace").setup({})
require("mini.indentscope").setup({})
require("mini.splitjoin").setup({})
require("mini.surround").setup({})

