require("brunhild.plugins.blink")
require("brunhild.plugins.telescope")
require("brunhild.plugins.treesitter")
require("brunhild.plugins.conform")
require("brunhild.plugins.dap")

require("gitsigns").setup({})
require("ibl").setup({})
require("lualine").setup({})
require("nvim-autopairs").setup({})
require("trouble").setup({})
require("colorizer").setup({})
require("Comment").setup({})
require("guess-indent").setup({})
require("dapui").setup({})
require("nvim-dap-virtual-text").setup({})

